"""
Single source of truth for all 107 product detail pages.
Consumed by generate-product-pages.py and wire-product-links.py.

Field notes:
- slug: kebab-case URL slug, derived from wa_name. Page lives at products/<slug>.html.
- wa_name: exact string already used in products.html's openWA('...') calls
  (taken from wire-product-images.py's PRODUCT_MAP) — used to match/wire the
  existing catalogue cards to their new detail page, and reused verbatim as
  the WhatsApp quote message product name so behavior doesn't change.
- name: display name (H1 / page title) — may include punctuation wa_name drops.
- brands: list of brand names shown on the catalogue card and product page.
- description: 2-4 hand-authored sentences.
- sizes: hand-authored list of realistic size/spec strings using correct
  units for the product category.
- Gallery extra images are derived from slug at render time
  (assets/images/products/extra/<slug>-2.jpg / -3.jpg) — not stored here.
"""

CATEGORIES = {
    "electrical":       {"title": "Electrical",       "icon": "⚡"},
    "cable-management": {"title": "Cable Management", "icon": "🔧"},
    "cables":           {"title": "Cables",            "icon": "🔌"},
    "plumbing":         {"title": "Plumbing",          "icon": "🚿"},
    "switch":           {"title": "Switch Sockets",    "icon": "💡"},
    "painting":         {"title": "Painting",          "icon": "🎨"},
    "tools":            {"title": "Tools",             "icon": "🔨"},
    "earthing":         {"title": "Earthing",          "icon": "⚡"},
    "sanitary":         {"title": "Sanitary",          "icon": "🚽"},
    "safety":           {"title": "Safety",            "icon": "🦺"},
    "hvac":             {"title": "HVAC",              "icon": "❄️"},
    "lighting":         {"title": "Lighting",          "icon": "🔆"},
    "pumps":            {"title": "Pumps",              "icon": "💧"},
    "hardware":         {"title": "Hardware",           "icon": "🔩"},
}

PRODUCTS = [
    # =========================== ELECTRICAL (7) ===========================
    {
        "slug": "modular-distribution-board-components",
        "wa_name": "Modular Distribution Board Components",
        "category": "electrical", "image": "prod-dist-board.jpg",
        "name": "Modular Distribution Board Components",
        "detail": "MCB, RCCB, RCBO, isolators for residential and commercial panels",
        "brands": ["ABB", "Hager"],
        "description": "Complete range of modular distribution board components — miniature circuit breakers (MCB), residual current circuit breakers (RCCB) and combined RCBO units — for reliable overload, short-circuit and earth-leakage protection in residential and light commercial panels. Sourced from ABB and Hager, all components are IEC 60898 / IEC 61009 compliant and suit DEWA and civil defence approved installations across the UAE.",
        "sizes": ["MCB: 1P/2P/3P/4P, 6A–63A, 6kA/10kA breaking capacity", "RCCB: 25A–100A, 30mA/100mA/300mA sensitivity, 2P/4P", "RCBO: 6A–40A combined MCB+RCD, 2P/4P", "Isolators: 20A–100A, 2P/3P/4P"],
    },
    {
        "slug": "main-distribution-panel-board-circuit-breakers",
        "wa_name": "Main Distribution Panel Board Circuit Breakers",
        "category": "electrical", "image": "prod-circuit-breaker.jpg",
        "name": "Main Distribution Panel Board Circuit Breakers",
        "detail": "ACB, MCCB for main distribution boards up to 6300A",
        "brands": ["Schneider", "ABB"],
        "description": "Air circuit breakers (ACB) and moulded case circuit breakers (MCCB) for main distribution boards, protecting incoming supply and main feeders in commercial and industrial installations. Schneider and ABB units offer adjustable thermal-magnetic and electronic trip units for precise coordination across the switchboard.",
        "sizes": ["MCCB: 16A–1600A, 3P/4P, 25kA–70kA breaking capacity", "ACB: 630A–6300A, fixed and withdrawable frames", "Trip units: thermal-magnetic and electronic (LSIG)", "Accessories: shunt trips, auxiliary contacts, motorised operators"],
    },
    {
        "slug": "load-break-isolators",
        "wa_name": "Load Break Isolators",
        "category": "electrical", "image": "prod-isolator.jpg",
        "name": "Load Break Isolators",
        "detail": "Enclosed isolators and changeover switches",
        "brands": ["Havells", "Alfanar"],
        "description": "Enclosed load break isolators and changeover switches for safe manual disconnection and source-changeover of electrical circuits under load. Havells and Alfanar units are IP65-rated where enclosed, suited to main incomer isolation, generator changeover and maintenance isolation points.",
        "sizes": ["Rating: 20A–1600A", "Poles: 2P/3P/4P", "Enclosure: IP65 metal/polycarbonate enclosed or panel-mount", "Type: on-load isolator, changeover (COS)"],
    },
    {
        "slug": "control-components",
        "wa_name": "Control Components",
        "category": "electrical", "image": "prod-control-panel.jpg",
        "name": "Control Components",
        "detail": "Contactors, relays, timers, push buttons, indicator lights",
        "brands": ["Schneider", "ABB"],
        "description": "Contactors, overload relays, timers, push buttons and indicator lights for motor control centres and control panels. Schneider and ABB ranges cover direct-on-line and star-delta starting, with accessories to build compliant control circuits for pumps, fans and other motor loads.",
        "sizes": ["Contactors: 9A–800A, coil voltages 24V–415V AC", "Overload relays: 0.1A–630A, adjustable thermal/electronic", "Timers: on-delay, off-delay, star-delta, 0.1s–100h", "Push buttons/indicators: 22mm mounting, IP65"],
    },
    {
        "slug": "power-factor-capacitor-bank-components",
        "wa_name": "Power Factor Capacitor Bank Components",
        "category": "electrical", "image": "prod-capacitor.jpg",
        "name": "Power Factor Capacitor Bank Components",
        "detail": "Capacitors, controllers, contactors for PFC panels",
        "brands": ["Alfanar"],
        "description": "Capacitors, automatic PFC controllers and switching contactors for building power factor correction panels, reducing reactive power charges and improving supply efficiency. Alfanar components are matched for automatic multi-step capacitor banks in commercial and industrial installations.",
        "sizes": ["Capacitors: 5kVAr–100kVAr per step, 415V/440V", "Controllers: 6-step to 12-step automatic relays", "Switching contactors: capacitor-duty rated", "Detuned reactor option: 5.7%/7% for harmonic-rich loads"],
    },
    {
        "slug": "distribution-boards-enclosures",
        "wa_name": "Distribution Boards &amp; Enclosures",
        "category": "electrical", "image": "prod-enclosure.jpg",
        "name": "Distribution Boards & Enclosures",
        "detail": "Flush and surface mounted consumer units and DB enclosures",
        "brands": ["Hager", "Schneider"],
        "description": "Flush and surface mounted consumer units, distribution board enclosures and metering panels for residential, commercial and industrial use. Hager and Schneider ranges include single and triple-phase boards with pre-punched cable entries and busbar systems ready for MCB/RCBO population.",
        "sizes": ["Ways: 4-way to 72-way single/triple phase", "Mounting: flush (recessed) or surface", "Material: powder-coated steel or fire-retardant polycarbonate", "IP rating: IP30 (indoor) to IP65 (outdoor)"],
    },
    {
        "slug": "panel-board-accessories",
        "wa_name": "Panel Board Accessories",
        "category": "electrical", "image": "prod-panel-acc.jpg",
        "name": "Panel Board Accessories",
        "detail": "Busbars, din rails, cable ducts, ferrules, terminal blocks",
        "brands": ["Havells", "ABB"],
        "description": "Busbars, DIN rails, cable ducts, ferrules and terminal blocks for assembling and finishing distribution and control panels to a professional standard. A one-stop range from Havells and ABB for panel builders and electrical contractors.",
        "sizes": ["Busbar: copper/aluminium, 12x2mm–100x10mm", "DIN rail: 35mm TS35 standard, 1m/2m lengths", "Terminal blocks: 2.5mm²–95mm², feed-through and earth", "Ferrules: 0.5mm²–16mm², numbered sets"],
    },

    # ======================= CABLE MANAGEMENT (8) =========================
    {
        "slug": "cable-glands-lugs-connectors",
        "wa_name": "Cable Glands Lugs &amp; Connectors",
        "category": "cable-management", "image": "prod-cable-gland.jpg",
        "name": "Cable Glands, Lugs & Connectors",
        "detail": "Brass, nickel-plated, stainless steel cable glands; compression lugs",
        "brands": ["Cellpack", "Bicon"],
        "description": "Brass, nickel-plated and stainless steel cable glands together with compression lugs and connectors for terminating armoured and unarmoured cables safely. Cellpack and Bicon ranges cover indoor and hazardous-area (Ex) applications with IP68 sealing options.",
        "sizes": ["Gland size: M16–M75, suits 6mm²–400mm² cables", "Material: brass, nickel-plated brass, 316 stainless steel", "Lugs: 1.5mm²–400mm², copper tinned/plain", "IP rating: IP66/IP68"],
    },
    {
        "slug": "cable-trays-ladders",
        "wa_name": "Cable Trays &amp; Ladders",
        "category": "cable-management", "image": "prod-cable-tray.jpg",
        "name": "Cable Trays & Ladders",
        "detail": "Hot-dip galvanized, perforated, solid bottom cable trays and ladders",
        "brands": ["Caparo", "Delta"],
        "description": "Hot-dip galvanized, perforated and solid-bottom cable trays and ladders for organised, supported cable routing in commercial and industrial buildings. Caparo and Delta systems include bends, tees and reducers for complete containment runs.",
        "sizes": ["Width: 50mm–900mm", "Depth: 25mm–150mm", "Finish: pre-galvanized, hot-dip galvanized, powder-coated", "Type: perforated tray, ladder tray, solid bottom tray"],
    },
    {
        "slug": "steel-support-systems",
        "wa_name": "Steel Support Systems",
        "category": "cable-management", "image": "prod-steel-support.jpg",
        "name": "Steel Support Systems",
        "detail": "Channel support, unistrut, cable clamps and fixings",
        "brands": ["Hex India", "BICC"],
        "description": "Channel support (unistrut-type) systems, cable clamps and fixing accessories for supporting cable trays, conduit and mechanical services. Hex India and BICC ranges suit both slotted and plain channel installations with a full range of brackets and fittings.",
        "sizes": ["Channel: 41x21mm, 41x41mm, 2m/3m/6m lengths", "Material: pre-galvanized or hot-dip galvanized steel", "Brackets: L-brackets, cantilever arms, base plates", "Cable clamps: single/double, 10mm–150mm cable diameter"],
    },
    {
        "slug": "pvc-conduit-trunking-systems",
        "wa_name": "PVC Conduit &amp; Trunking Systems",
        "category": "cable-management", "image": "prod-conduit-pvc.jpg",
        "name": "PVC Conduit & Trunking Systems",
        "detail": "Heavy gauge PVC conduit, trunking, accessories in all sizes",
        "brands": ["Decoduct", "Unitech"],
        "description": "Heavy-gauge PVC conduit and trunking with a full range of accessories for concealed and surface electrical wiring. Decoduct and Unitech systems are self-extinguishing, corrosion-resistant and suited to both domestic and commercial installations.",
        "sizes": ["Conduit diameter: 16mm–50mm", "Trunking: 16x16mm–100x50mm, single/dual compartment", "Length: 3m standard lengths", "Accessories: bends, tees, couplers, saddles, boxes"],
    },
    {
        "slug": "cable-ties-pulling-springs",
        "wa_name": "Cable Ties &amp; Pulling Springs",
        "category": "cable-management", "image": "prod-cable-ties.jpg",
        "name": "Cable Ties & Pulling Springs",
        "detail": "Nylon cable ties in all sizes; steel cable pulling springs",
        "brands": ["Yuvix"],
        "description": "Nylon cable ties in a full range of sizes for bundling and securing cables, plus steel cable pulling springs (fish tapes) for drawing cables through conduit runs. A Yuvix-supplied essential for any cable installation crew.",
        "sizes": ["Cable ties: 100mm–600mm, natural and UV black", "Tensile strength: 8kg–50kg", "Pulling springs: 5m–30m coil lengths", "Diameter: 3mm–4.5mm steel wire"],
    },
    {
        "slug": "floor-distribution-systems",
        "wa_name": "Floor Distribution Systems",
        "category": "cable-management", "image": "prod-floor-dist.jpg",
        "name": "Floor Distribution Systems",
        "detail": "Underfloor cable distribution boxes and accessories",
        "brands": ["Marshall Tufflex"],
        "description": "Underfloor cable distribution boxes, floor outlet boxes and access covers for delivering power and data to open-plan offices and raised-floor installations. Marshall Tufflex systems integrate with raised access floor tiles for a flush, tidy finish.",
        "sizes": ["Floor boxes: 2-gang to 6-gang configurations", "Depth: suits 50mm–150mm floor void", "Finish: brushed steel, brass, carpet-flush lid", "Outlets: power, data, AV combination modules"],
    },
    {
        "slug": "cable-jointing-systems",
        "wa_name": "Cable Jointing Systems",
        "category": "cable-management", "image": "prod-cable-joint.jpg",
        "name": "Cable Jointing Systems",
        "detail": "Heat shrink, cold shrink joints and termination kits",
        "brands": ["Cellpack", "BICC"],
        "description": "Heat-shrink and cold-shrink jointing kits and termination kits for LV and MV cable splicing and end termination. Cellpack and BICC kits give a fully insulated, weatherproof, mechanically protected joint for underground and indoor cable runs.",
        "sizes": ["Voltage range: LV (0.6/1kV) to MV (11kV/33kV)", "Cable size range: 25mm²–400mm²", "Type: heat-shrink, cold-shrink, resin-filled joints", "Cores: 1-core to 4-core kits"],
    },
    {
        "slug": "steel-conduit-wiring-boxes",
        "wa_name": "Steel Conduit &amp; Wiring Boxes",
        "category": "cable-management", "image": "prod-steel-conduit.jpg",
        "name": "Steel Conduit & Wiring Boxes",
        "detail": "GI steel conduit, junction boxes, pull boxes",
        "brands": ["Unitech", "Delta"],
        "description": "Galvanised iron (GI) steel conduit with matching junction and pull boxes for wiring installations requiring mechanical protection, such as exposed industrial runs and hazardous areas. Unitech and Delta ranges are threaded to BS 4568 for secure fitting connections.",
        "sizes": ["Conduit diameter: 20mm–50mm (BS 4568)", "Wall thickness: heavy gauge screwed and plain", "Boxes: junction, pull, adaptable, sizes 75mm–150mm", "Finish: hot-dip galvanized"],
    },

    # ============================= CABLES (9) ==============================
    {
        "slug": "solar-cables",
        "wa_name": "Solar Cables",
        "category": "cables", "image": "prod-solar-cable.jpg",
        "name": "Solar Cables",
        "detail": "PV1-F solar DC cables, UV resistant, double insulated",
        "brands": ["Nexans", "Prysmian"],
        "description": "PV1-F single-core solar DC cables, UV and weather resistant with double insulation, for connecting photovoltaic panels to inverters and combiner boxes. Nexans and Prysmian solar cables are rated for 25+ years of outdoor exposure typical of UAE rooftop and ground-mount solar installations.",
        "sizes": ["Conductor size: 2.5mm²–16mm²", "Voltage rating: 1.5kV DC / 1kV AC", "Temperature range: -40°C to +120°C", "Colour: red (positive), black (negative)"],
    },
    {
        "slug": "co-axial-cables",
        "wa_name": "Co-axial Cables",
        "category": "cables", "image": "prod-coaxial.jpg",
        "name": "Co-axial Cables",
        "detail": "RG6, RG11, RG59 coaxial cables for TV and CCTV",
        "brands": ["Belden", "D-Link"],
        "description": "RG6, RG11 and RG59 coaxial cables for terrestrial TV, satellite and CCTV signal distribution. Belden and D-Link cables offer low signal loss with copper-clad steel or solid copper conductors for reliable long-run performance.",
        "sizes": ["RG6: 75Ω, standard and quad-shield", "RG11: 75Ω, low-loss long-distance runs", "RG59: 75Ω, CCTV and short-run video", "Jacket: PVC or LSZH, indoor/outdoor rated"],
    },
    {
        "slug": "single-core-wires",
        "wa_name": "Single Core Wires",
        "category": "cables", "image": "prod-single-wire.jpg",
        "name": "Single Core Wires",
        "detail": "1.5mm² to 300mm² single core PVC and XLPE insulated",
        "brands": ["Ducab", "CopperPlus"],
        "description": "Single core copper conductor wires, PVC and XLPE insulated, for general power and lighting circuit wiring in buildings. Ducab and CopperPlus wires are manufactured to BS 6004/BS 7211 and available in the full colour range for phase, neutral and earth identification.",
        "sizes": ["Conductor size: 1.5mm² – 300mm²", "Insulation: PVC (BS 6004) or XLPE (BS 7211)", "Colours: red, yellow, blue, black, green/yellow", "Stranding: solid and stranded conductor options"],
    },
    {
        "slug": "xlpe-insulated-cables",
        "wa_name": "XLPE Insulated Cables",
        "category": "cables", "image": "prod-xlpe-cable.jpg",
        "name": "XLPE Insulated Cables",
        "detail": "0.6/1kV to 33kV XLPE power cables, armoured and unarmoured",
        "brands": ["Ducab", "Nexans"],
        "description": "Cross-linked polyethylene (XLPE) insulated power cables rated 0.6/1kV to 33kV, for underground and duct-run distribution in residential, commercial and industrial projects. Available in single-core and multi-core, armoured (SWA/AWA) and unarmoured constructions with stranded copper or aluminium conductors, manufactured to BS 5467 / IEC 60502.",
        "sizes": ["Conductor size: 1.5mm² – 630mm² (Cu), 25mm² – 630mm² (Al)", "Voltage grade: 0.6/1kV, 3.3kV, 6.6kV, 11kV, 33kV", "Cores: 1C, 2C, 3C, 3.5C, 4C", "Armour: SWA (steel wire), AWA (aluminium wire), unarmoured"],
    },
    {
        "slug": "fire-performance-cables",
        "wa_name": "Fire Performance Cables",
        "category": "cables", "image": "prod-fire-cable.jpg",
        "name": "Fire Performance Cables",
        "detail": "Fire resistant, LSZH, Enhanced Fire cables to BS standards",
        "brands": ["Prysmian", "Top Cable"],
        "description": "Fire-resistant and low smoke zero halogen (LSZH) cables designed to maintain circuit integrity during fire, used for emergency lighting, fire alarm and life-safety circuits. Prysmian and Top Cable ranges are tested to BS 7629 / BS 8434 fire survival standards required in UAE civil defence approved buildings.",
        "sizes": ["Conductor size: 1.5mm²–4mm² (control), up to 300mm² (power)", "Standard: BS 7629 / BS 8434 fire resistant, LSZH sheath", "Cores: 2-core to 4-core plus earth", "Circuit integrity: 120 minutes fire survival"],
    },
    {
        "slug": "multicore-industrial-cables",
        "wa_name": "Multicore Industrial Cables",
        "category": "cables", "image": "prod-multicore.jpg",
        "name": "Multicore Industrial Cables",
        "detail": "2 to 61 core control cables, screened and unscreened",
        "brands": ["Belden", "Oman Cables"],
        "description": "Multicore control and instrumentation cables with 2 to 61 cores, screened and unscreened, for industrial control panels, automation and process instrumentation wiring. Belden and Oman Cables constructions minimise electrical interference in noisy industrial environments.",
        "sizes": ["Cores: 2-core to 61-core", "Conductor size: 0.5mm²–2.5mm²", "Screening: individually screened, overall braid/foil", "Sheath: PVC or LSZH"],
    },
    {
        "slug": "rubber-welding-cables",
        "wa_name": "Rubber &amp; Welding Cables",
        "category": "cables", "image": "prod-welding-cable.jpg",
        "name": "Rubber & Welding Cables",
        "detail": "Flexible rubber cables, welding cables, EPR insulated",
        "brands": ["Nexans", "CopperPlus"],
        "description": "Flexible EPR-insulated rubber cables and dedicated welding cables built for heavy flexing, high current and tough site conditions. Nexans and CopperPlus cables suit portable equipment, generator tails and arc welding machine connections.",
        "sizes": ["Welding cable: 16mm²–120mm², yellow/black jacket", "Rubber flexible cable: 1.5mm²–95mm², H07RN-F type", "Voltage: 450/750V", "Temperature range: -25°C to +85°C"],
    },
    {
        "slug": "panel-switchboard-battery-cables",
        "wa_name": "Panel Switchboard &amp; Battery Cables",
        "category": "cables", "image": "prod-battery-cable.jpg",
        "name": "Panel, Switchboard & Battery Cables",
        "detail": "Flexible panel wiring cables, battery interconnect cables",
        "brands": ["Ducab", "Paige"],
        "description": "Flexible panel wiring cables and heavy-duty battery/interconnect cables with copper lugs, used inside switchboards, UPS rooms and battery banks. Ducab and Paige cables provide low-voltage-drop connections for high-current DC and control wiring.",
        "sizes": ["Panel wire: 0.5mm²–6mm², multi-strand flexible", "Battery cable: 16mm²–185mm², tinned copper", "Lugs: pre-crimped or supplied loose", "Voltage: 600V/1000V rated"],
    },
    {
        "slug": "data-fibre-optic-instrumentation-cables",
        "wa_name": "Data Fibre-optic &amp; Instrumentation Cables",
        "category": "cables", "image": "prod-fiber-optic.jpg",
        "name": "Data, Fibre-optic & Instrumentation Cables",
        "detail": "Cat6, Cat6A, OS2 fibre, PLTC instrumentation cables",
        "brands": ["Belden", "D-Link"],
        "description": "Structured data cabling (Cat6/Cat6A), OS2 single-mode fibre optic cable and PLTC instrumentation cable for networking, telecoms and process control infrastructure. Belden and D-Link products support high-bandwidth office networks and long-distance fibre backbone runs alike.",
        "sizes": ["Cat6/Cat6A: UTP/FTP, 305m box, up to 10Gbps", "Fibre optic: OS2 single-mode, OM3/OM4 multi-mode", "Instrumentation: PLTC 1-pair to 24-pair, shielded", "Jacket: LSZH/PVC, indoor-outdoor rated"],
    },

    # ============================ PLUMBING (7) =============================
    {
        "slug": "ppr-pipes-fittings",
        "wa_name": "PPR Pipes &amp; Fittings",
        "category": "plumbing", "image": "prod-ppr-pipe.jpg",
        "name": "PPR Pipes & Fittings",
        "detail": "PN20 PPR pipes and fittings for hot and cold water systems",
        "brands": ["Novatherm", "RAKtherm"],
        "description": "PN20-rated polypropylene random copolymer (PPR) pipes and fittings for hot and cold domestic water supply systems. Fusion-welded joints give a leak-free, corrosion-resistant network suitable for concealed and exposed installation, compliant with DIN 8077/8078.",
        "sizes": ["Diameter: 20mm, 25mm, 32mm, 40mm, 50mm, 63mm, 75mm, 90mm, 110mm", "Pressure rating: PN10, PN16, PN20, PN25", "Fittings: elbows, tees, couplers, reducers, unions, ball valves"],
    },
    {
        "slug": "upvc-pipes-fittings",
        "wa_name": "UPVC Pipes &amp; Fittings",
        "category": "plumbing", "image": "prod-upvc-pipe.jpg",
        "name": "UPVC Pipes & Fittings",
        "detail": "UPVC pressure pipes, Class B, C and D for water supply",
        "brands": ["Hepworth", "Cosmoplast"],
        "description": "UPVC pressure pipes in Class B, C and D for cold water supply and general plumbing distribution. Hepworth and Cosmoplast pipes are solvent-weld or push-fit jointed, lightweight and corrosion resistant for long service life.",
        "sizes": ["Diameter: 20mm–315mm", "Pressure class: Class B (6 bar), Class C (9 bar), Class D (12 bar)", "Length: 3m/6m standard lengths", "Jointing: solvent cement weld, rubber ring push-fit"],
    },
    {
        "slug": "hdpe-pipes-fittings",
        "wa_name": "HDPE Pipes &amp; Fittings",
        "category": "plumbing", "image": "prod-hdpe-pipe.jpg",
        "name": "HDPE Pipes & Fittings",
        "detail": "PE100 HDPE pipes for water mains and sewerage",
        "brands": ["Prime", "Cosmoplast"],
        "description": "PE100 high density polyethylene pipes and butt-fusion/electrofusion fittings for water mains, sewerage and irrigation networks. Prime and Cosmoplast HDPE piping resists corrosion and ground movement, suited to both above- and below-ground installation.",
        "sizes": ["Diameter: 20mm–630mm", "Pressure rating: PN6–PN16 (PE100)", "Jointing: butt fusion, electrofusion", "Coils: 50m/100m (small bore), straight lengths (large bore)"],
    },
    {
        "slug": "pex-pipes",
        "wa_name": "Pex Pipes",
        "category": "plumbing", "image": "prod-pex-pipe.jpg",
        "name": "Pex Pipes",
        "detail": "Cross-linked polyethylene pipes for underfloor heating and plumbing",
        "brands": ["RAKtherm"],
        "description": "Cross-linked polyethylene (PEX) pipes for underfloor heating, hot/cold water plumbing and radiant systems, supplied in flexible coils with brass compression or press fittings. RAKtherm PEX resists scale build-up and offers a long, maintenance-free service life.",
        "sizes": ["Diameter: 16mm–32mm", "Coil length: 100m, 200m, 500m", "Pressure rating: PN10/PN16, tested to 95°C", "Fittings: brass compression, press-fit"],
    },
    {
        "slug": "pvc-white-pipes",
        "wa_name": "PVC White Pipes",
        "category": "plumbing", "image": "prod-pvc-pipe.jpg",
        "name": "PVC White Pipes",
        "detail": "PVC conduit and pipe systems for general plumbing",
        "brands": ["Cosmoplast", "Prime"],
        "description": "General-purpose white PVC pipe and conduit systems for plumbing, waste and light electrical containment applications. Cosmoplast and Prime pipes are UV-stabilised for exposed outdoor runs and solvent-weld jointed for a secure connection.",
        "sizes": ["Diameter: 20mm–160mm", "Wall thickness: schedule 40 / schedule 80 options", "Length: 3m/6m", "Jointing: solvent cement weld"],
    },
    {
        "slug": "high-pressure-pipes",
        "wa_name": "High Pressure Pipes",
        "category": "plumbing", "image": "prod-hp-pipe.jpg",
        "name": "High Pressure Pipes",
        "detail": "High pressure water supply systems for industrial applications",
        "brands": ["Hepworth"],
        "description": "High-pressure steel and reinforced pipe systems for industrial water supply, fire-fighting mains and process applications demanding higher working pressures than standard plumbing pipe. Hepworth's high-pressure range is specified for pump discharge lines and elevated-building risers.",
        "sizes": ["Diameter: 25mm–300mm", "Pressure rating: PN16–PN25", "Material: galvanized steel / reinforced HDPE", "Jointing: threaded, flanged, grooved"],
    },
    {
        "slug": "drainage-pipes-systems",
        "wa_name": "Drainage Pipes &amp; Systems",
        "category": "plumbing", "image": "prod-drainage.jpg",
        "name": "Drainage Pipes & Systems",
        "detail": "UPVC soil and waste drainage, underground drainage pipes",
        "brands": ["Terrain", "Hepworth"],
        "description": "UPVC soil, waste and underground drainage pipe systems for building sanitary drainage and site stormwater networks. Terrain and Hepworth ranges include the full complement of bends, junctions, gullies and access fittings for a complete drainage layout.",
        "sizes": ["Soil/waste diameter: 32mm–160mm", "Underground diameter: 110mm–400mm", "Standard: BS EN 1329 (soil/waste), BS EN 1401 (underground)", "Fittings: bends, junctions, access pipes, gullies"],
    },

    # ========================== SWITCH SOCKETS (7) =========================
    {
        "slug": "waterproof-switch-sockets",
        "wa_name": "Waterproof Switch Sockets",
        "category": "switch", "image": "prod-switch-wp.jpg",
        "name": "Waterproof Switch Sockets",
        "detail": "IP44 and IP66 rated weatherproof switches and sockets",
        "brands": ["ABB", "Schneider"],
        "description": "IP44 and IP66-rated weatherproof switches and socket outlets for outdoor, bathroom, kitchen and industrial wet-area installations. ABB and Schneider ranges feature sealed gaskets and robust enclosures for long-term protection against moisture and dust.",
        "sizes": ["IP rating: IP44, IP55, IP66", "Configuration: 1-gang to 4-gang switches, 13A/16A/32A sockets", "Poles: single pole, double pole", "Enclosure: surface-mount weatherproof box"],
    },
    {
        "slug": "pop-up-switches",
        "wa_name": "Pop-up Switches",
        "category": "switch", "image": "prod-popup-switch.jpg",
        "name": "Pop-up Switches",
        "detail": "Flush pop-up socket outlets for desks and worktops",
        "brands": ["Legrand"],
        "description": "Flush-mounted pop-up socket outlets that retract into desks, worktops and floor boxes when not in use, keeping power and data access neat and out of sight. Legrand pop-up units combine power, USB and data modules in a single retractable housing.",
        "sizes": ["Configuration: 2-way to 6-way modular", "Modules: 13A socket, USB charger, HDMI/data", "Finish: brushed steel, matte black, white", "Mounting: desktop, worktop, floor box"],
    },
    {
        "slug": "switch-sockets-standard",
        "wa_name": "Switch Sockets Standard",
        "category": "switch", "image": "prod-socket.jpg",
        "name": "Switch Sockets (Standard)",
        "detail": "1G, 2G, 3G switches and 13A socket outlets, various finishes",
        "brands": ["MK", "Crabtree"],
        "description": "Standard 1-gang, 2-gang and 3-gang wall switches and 13A socket outlets for general residential and commercial wiring, available in a range of finishes to match interior design. MK and Crabtree ranges are BS 1363/BS 3676 compliant.",
        "sizes": ["Switch gang: 1G, 2G, 3G, 1-way/2-way", "Socket rating: 13A single/twin, switched", "Finish: white moulded, brushed steel, chrome", "Mounting: flush (surface plate) or surface box"],
    },
    {
        "slug": "smart-switches",
        "wa_name": "Smart Switches",
        "category": "switch", "image": "prod-smart-switch.jpg",
        "name": "Smart Switches",
        "detail": "Wi-Fi enabled smart switches compatible with Alexa and Google",
        "brands": ["Schneider", "Panasonic"],
        "description": "Wi-Fi enabled smart switches with app and voice control (Alexa, Google Assistant), allowing lighting and appliance circuits to be scheduled and controlled remotely. Schneider and Panasonic smart ranges retrofit into standard wall boxes without a neutral-wire requirement in most models.",
        "sizes": ["Load rating: up to 10A per gang", "Connectivity: Wi-Fi 2.4GHz, Bluetooth pairing", "Control: app, voice assistant, physical touch", "Gang configuration: 1-gang to 4-gang"],
    },
    {
        "slug": "grid-switches-modules",
        "wa_name": "Grid Switches &amp; Modules",
        "category": "switch", "image": "prod-grid-switch.jpg",
        "name": "Grid Switches & Modules",
        "detail": "Grid switch systems for modular wiring installations",
        "brands": ["MK", "Legrand"],
        "description": "Modular grid switch systems allowing multiple switch, socket, dimmer and data modules to be combined on a single plate for flexible wiring layouts. MK and Legrand grid systems are popular for kitchens, media walls and commercial fit-outs needing custom configurations.",
        "sizes": ["Grid size: 1-gang to 12-module plates", "Modules: switch, dimmer, socket, blank, data", "Frame: metal or moulded grid frame", "Finish: white, brushed steel, black nickel"],
    },
    {
        "slug": "metal-clad-switches",
        "wa_name": "Metal Clad Switches",
        "category": "switch", "image": "prod-metal-switch.jpg",
        "name": "Metal Clad Switches",
        "detail": "Industrial grade metal clad switches for commercial use",
        "brands": ["ABB", "Crabtree"],
        "description": "Industrial-grade metal clad switches and isolators in robust galvanized steel enclosures for workshops, plant rooms and exposed commercial areas subject to mechanical damage risk. ABB and Crabtree metal clad units offer IP54+ protection with positive isolation indication.",
        "sizes": ["Rating: 20A–100A", "Poles: 1P, 2P, 3P, 3P+N", "Enclosure: IP54/IP65 galvanized steel", "Mounting: surface wall mount"],
    },
    {
        "slug": "isolators",
        "wa_name": "Isolators",
        "category": "switch", "image": "prod-sw-isolator.jpg",
        "name": "Isolators",
        "detail": "DP and TP switch isolators for A/C and equipment isolation",
        "brands": ["MK", "Schneider"],
        "description": "Double-pole and triple-pole switch isolators for local isolation of air-conditioning units, water heaters and fixed appliances, as required by wiring regulations for maintenance safety. MK and Schneider isolators are available in flush and surface mount formats.",
        "sizes": ["Rating: 20A–63A", "Poles: DP (double pole), TP (triple pole)", "Type: flex outlet plate, fused/unfused", "Mounting: flush or surface"],
    },

    # ============================ PAINTING (9) ==============================
    {
        "slug": "anti-fungal-anti-bacterial-paint",
        "wa_name": "Anti-Fungal Anti-Bacterial Paint",
        "category": "painting", "image": "prod-antifungal-paint.jpg",
        "name": "Anti-Fungal / Anti-Bacterial Paint",
        "detail": "Moisture resistant paint for bathrooms, kitchens and hospitals",
        "brands": ["Jotun", "Asian Paints"],
        "description": "Moisture-resistant, anti-fungal and anti-bacterial wall paint formulated to inhibit mould and bacterial growth in bathrooms, kitchens, hospitals and other high-humidity spaces. Jotun and Asian Paints formulations are washable and suited to UAE's high-humidity climate.",
        "sizes": ["Pack size: 1L, 4L, 20L", "Coverage: approx. 12–14 sq.m/L per coat", "Finish: matt, silk, semi-gloss", "Recommended coats: 2 coats over suitable primer"],
    },
    {
        "slug": "exterior-emulsion",
        "wa_name": "Exterior Emulsion",
        "category": "painting", "image": "prod-exterior-paint.jpg",
        "name": "Exterior Emulsion",
        "detail": "Weather resistant exterior wall emulsion for facades",
        "brands": ["Jotun", "National"],
        "description": "Weather-resistant exterior wall emulsion formulated to withstand UAE's intense UV exposure, heat and occasional rain, protecting facades from fading, cracking and dirt pickup. Jotun and National exterior ranges offer extended colour retention warranties.",
        "sizes": ["Pack size: 1L, 4L, 18L, 20L", "Coverage: approx. 10–12 sq.m/L per coat", "Finish: matt, silk, weathershield", "Recommended coats: 2 coats over primer/sealer"],
    },
    {
        "slug": "interior-emulsion",
        "wa_name": "Interior Emulsion",
        "category": "painting", "image": "prod-interior-paint.jpg",
        "name": "Interior Emulsion",
        "detail": "Smooth finish interior emulsion, washable, low VOC",
        "brands": ["Jotun", "Asian Paints"],
        "description": "Smooth-finish, washable, low-VOC interior emulsion for walls and ceilings in residential and commercial interiors. Jotun and Asian Paints interior ranges offer excellent hide and a wide standard and tinted colour range.",
        "sizes": ["Pack size: 1L, 4L, 18L, 20L", "Coverage: approx. 12–14 sq.m/L per coat", "Finish: matt, silk, soft sheen", "VOC: low-VOC formulation"],
    },
    {
        "slug": "fenomastic-paint",
        "wa_name": "Fenomastic Paint",
        "category": "painting", "image": "prod-fenomastic.jpg",
        "name": "Fenomastic Paint",
        "detail": "Jotun Fenomastic pure colours interior and exterior range",
        "brands": ["Jotun"],
        "description": "Jotun's Fenomastic Pure Colours range delivers premium, richly-pigmented interior and exterior emulsions with a smooth, durable finish and a wide designer colour palette. A popular choice for villas and commercial interiors seeking a premium paint specification.",
        "sizes": ["Pack size: 1L, 4L, 18L", "Coverage: approx. 13–15 sq.m/L per coat", "Finish: matt, silk", "Range: interior and exterior formulations"],
    },
    {
        "slug": "emulsion-paint",
        "wa_name": "Emulsion Paint",
        "category": "painting", "image": "prod-emulsion.jpg",
        "name": "Emulsion Paint",
        "detail": "Standard emulsion in a wide range of colours",
        "brands": ["National", "Asian Paints"],
        "description": "Standard-grade emulsion paint in a wide range of ready-mixed and tinted colours, suitable for general interior wall decoration on budget-conscious projects. National and Asian Paints emulsion ranges offer reliable coverage and easy application by brush, roller or spray.",
        "sizes": ["Pack size: 1L, 4L, 20L", "Coverage: approx. 10–12 sq.m/L per coat", "Finish: matt, silk", "Recommended coats: 2 coats"],
    },
    {
        "slug": "texture-paint",
        "wa_name": "Texture Paint",
        "category": "painting", "image": "prod-texture-paint.jpg",
        "name": "Texture Paint",
        "detail": "Sand texture, coarse texture, rough cast finish paints",
        "brands": ["Jotun", "National"],
        "description": "Sand texture, coarse texture and rough-cast finish paints for creating decorative, dimensional wall surfaces both internally and on facades. Jotun and National texture ranges are applied by trowel, roller or spray gun depending on the desired finish.",
        "sizes": ["Pack size: 20kg, 25kg buckets", "Coverage: approx. 2–4 sq.m/kg depending on texture grade", "Texture grade: fine, medium, coarse sand finish", "Application: trowel, roller, spray"],
    },
    {
        "slug": "enamel-paint",
        "wa_name": "Enamel Paint",
        "category": "painting", "image": "prod-enamel-paint.jpg",
        "name": "Enamel Paint",
        "detail": "Gloss and semi-gloss enamel for wood, metal and trim",
        "brands": ["Asian Paints", "Jotun"],
        "description": "Gloss and semi-gloss enamel paint for wood and metal surfaces, including doors, grilles, railings and structural steelwork, offering a hard-wearing, easy-to-clean finish. Asian Paints and Jotun enamel ranges include synthetic and quick-dry formulations.",
        "sizes": ["Pack size: 1L, 4L, 20L", "Coverage: approx. 12–14 sq.m/L per coat", "Finish: gloss, semi-gloss", "Substrate: wood, metal, previously painted surfaces"],
    },
    {
        "slug": "primers-undercoats",
        "wa_name": "Primers &amp; Undercoats",
        "category": "painting", "image": "prod-primer.jpg",
        "name": "Primers & Undercoats",
        "detail": "Alkali resistant primer, wall filler, sealer and undercoat",
        "brands": ["Jotun", "National"],
        "description": "Alkali-resistant wall primers, fillers, sealers and metal undercoats that prepare surfaces for topcoat application, improving adhesion, coverage and finish uniformity. Jotun and National primers are matched to their respective emulsion and enamel topcoat systems.",
        "sizes": ["Pack size: 1L, 4L, 20L", "Coverage: approx. 10–12 sq.m/L per coat", "Type: alkali-resistant wall primer, metal undercoat, sealer", "Dry time: 4–6 hours recoat"],
    },
    {
        "slug": "wall-putty",
        "wa_name": "Wall Putty",
        "category": "painting", "image": "prod-wall-putty.jpg",
        "name": "Wall Putty",
        "detail": "White cement based wall putty for smooth surface preparation",
        "brands": ["Asian Paints"],
        "description": "White cement based wall putty from Asian Paints for filling minor surface imperfections and achieving a smooth, paint-ready finish on interior and exterior masonry and plaster surfaces. High bonding strength, crack-resistant and low water absorption for a durable base coat before emulsion or enamel application.",
        "sizes": ["Pack sizes: 5kg, 20kg, 40kg bags", "Coverage: approx. 18–20 sq.ft./kg per coat", "Recommended: 2 coats, total dry film thickness 1–1.5mm"],
    },

    # ============================== TOOLS (10) ==============================
    {
        "slug": "impact-wrench",
        "wa_name": "Impact Wrench",
        "category": "tools", "image": "prod-impact-wrench.jpg",
        "name": "Impact Wrench",
        "detail": "Cordless and corded impact wrenches, various torque ratings",
        "brands": ["Makita", "DeWalt"],
        "description": "Cordless and corded impact wrenches for high-torque bolt tightening and loosening in construction, fabrication and vehicle maintenance work. Makita and DeWalt ranges offer variable torque settings and brushless motor options for extended run time.",
        "sizes": ["Drive size: 1/2\", 3/4\", 1\"", "Max torque: 200Nm–1,600Nm", "Power: 18V/20V cordless, 110V/220V corded", "Battery: 2.0Ah–6.0Ah Li-ion (cordless models)"],
    },
    {
        "slug": "angle-grinders",
        "wa_name": "Angle Grinders",
        "category": "tools", "image": "prod-angle-grinder.jpg",
        "name": "Angle Grinders",
        "detail": "4.5\", 5\" and 9\" angle grinders for cutting and grinding",
        "brands": ["Bosch", "Makita"],
        "description": "4.5-inch, 5-inch and 9-inch angle grinders for cutting, grinding and surface preparation of metal, concrete and stone. Bosch and Makita grinders include corded and cordless models with safety guards and anti-kickback protection.",
        "sizes": ["Disc diameter: 4.5\" (115mm), 5\" (125mm), 9\" (230mm)", "Power: 720W–2,400W corded, 18V cordless", "No-load speed: 6,000–11,000 rpm", "Spindle: M14 thread"],
    },
    {
        "slug": "power-tools-general",
        "wa_name": "Power Tools General",
        "category": "tools", "image": "prod-power-tools.jpg",
        "name": "Power Tools (General)",
        "detail": "Sanders, routers, planers and general power tools",
        "brands": ["DeWalt", "Bosch"],
        "description": "General-purpose power tools including sanders, routers and planers for finishing and shaping wood, metal and composite materials on site or in the workshop. DeWalt and Bosch ranges cover both corded and battery-platform cordless options.",
        "sizes": ["Sanders: orbital, belt, random orbit", "Planers: 82mm–110mm cutting width", "Power: 500W–1,200W corded, 18V/20V cordless", "Accessories: sanding discs, planer blades"],
    },
    {
        "slug": "hand-tools",
        "wa_name": "Hand Tools",
        "category": "tools", "image": "prod-hand-tools.jpg",
        "name": "Hand Tools",
        "detail": "Pliers, screwdrivers, spanners, wrenches and hand tool sets",
        "brands": ["Stanley", "DeWalt"],
        "description": "Pliers, screwdrivers, spanners, wrenches and general hand tool sets for site, workshop and maintenance work. Stanley and DeWalt hand tools are forged from chrome vanadium steel for durability and offer both individual pieces and boxed sets.",
        "sizes": ["Sets: 20-piece to 100-piece tool kits", "Spanner sizes: 6mm–32mm / 1/4\"–1-1/4\"", "Screwdrivers: flathead, Phillips, Torx, insulated (VDE)", "Material: chrome vanadium steel"],
    },
    {
        "slug": "tool-accessories",
        "wa_name": "Tool Accessories",
        "category": "tools", "image": "prod-tool-acc.jpg",
        "name": "Tool Accessories",
        "detail": "Drill bits, grinding discs, cutting discs, saw blades",
        "brands": ["Bosch", "Makita"],
        "description": "Drill bits, grinding discs, cutting discs and saw blades sized and specified for a wide range of power tool applications across metal, wood, masonry and tile. Bosch and Makita accessory ranges are matched to their respective tool platforms for optimal performance.",
        "sizes": ["Drill bits: HSS, masonry, SDS — 3mm–32mm", "Cutting/grinding discs: 115mm–230mm diameter", "Saw blades: circular, jigsaw, reciprocating — various TPI", "Material: for metal, wood, masonry, tile"],
    },
    {
        "slug": "drills-hammer-drills",
        "wa_name": "Drills &amp; Hammer Drills",
        "category": "tools", "image": "prod-drill.jpg",
        "name": "Drills & Hammer Drills",
        "detail": "Cordless drill drivers, SDS-plus and SDS-max rotary hammers",
        "brands": ["Makita", "Hilti"],
        "description": "Cordless drill drivers and SDS-plus/SDS-max rotary hammers for drilling into wood, metal, masonry and concrete. Makita and Hilti ranges span light-duty cordless drivers up to heavy industrial demolition-rated rotary hammers.",
        "sizes": ["Drill driver: 10mm–13mm chuck, 12V–18V", "SDS-plus: up to 26mm concrete drilling", "SDS-max: up to 52mm concrete drilling", "Impact energy: 1.5J–12J depending on model"],
    },
    {
        "slug": "routers",
        "wa_name": "Routers",
        "category": "tools", "image": "prod-router.jpg",
        "name": "Routers",
        "detail": "Fixed base and plunge routers for woodworking",
        "brands": ["Bosch", "Makita"],
        "description": "Fixed-base and plunge routers for edge profiling, grooving and joinery work in wood and composite materials. Bosch and Makita router ranges accept a wide range of router bit collets and depth-stop accessories.",
        "sizes": ["Collet size: 6mm, 8mm, 1/4\", 1/2\"", "Power: 900W–2,100W", "Router type: fixed-base, plunge, trimmer", "Speed: variable, 8,000–25,000 rpm"],
    },
    {
        "slug": "chop-saws-miter-saws",
        "wa_name": "Chop Saws Miter Saws",
        "category": "tools", "image": "prod-miter-saw.jpg",
        "name": "Chop Saws (Miter Saws)",
        "detail": "Sliding compound miter saws for accurate cross cuts",
        "brands": ["DeWalt", "Makita"],
        "description": "Sliding compound miter saws for accurate angled and straight cross-cuts in timber, aluminium and light metal sections. DeWalt and Makita miter saws feature laser guides and dust extraction ports for precise, clean cutting.",
        "sizes": ["Blade diameter: 210mm, 254mm, 305mm", "Max cross-cut width: 60mm–340mm", "Miter/bevel range: 0°–48° miter, 0°–48° bevel", "Power: 1,400W–1,800W"],
    },
    {
        "slug": "jig-saws",
        "wa_name": "Jig Saws",
        "category": "tools", "image": "prod-jigsaw.jpg",
        "name": "Jig Saws",
        "detail": "Orbital and straight cut jig saws for curves and shapes",
        "brands": ["Bosch", "DeWalt"],
        "description": "Orbital and straight-cut jig saws for cutting curves, cut-outs and irregular shapes in wood, laminate and thin metal. Bosch and DeWalt jig saws offer tool-free blade change and variable orbital action for finish control.",
        "sizes": ["Stroke length: 18mm–26mm", "Cutting depth: wood up to 135mm, steel up to 10mm", "Power: 500W–800W corded, 18V cordless", "Blade type: T-shank quick-change"],
    },
    {
        "slug": "hilti-systems",
        "wa_name": "Hilti Systems",
        "category": "tools", "image": "prod-hilti.jpg",
        "name": "Hilti Systems",
        "detail": "Hilti anchor systems, fastening, cutting and measuring tools",
        "brands": ["Hilti"],
        "description": "Genuine Hilti anchor systems, fastening tools, diamond cutting/coring equipment and laser measuring tools for professional construction applications requiring certified performance data. Hilti systems are specified where engineered anchor approvals and traceability are required.",
        "sizes": ["Anchors: mechanical expansion, chemical injection, M6–M24", "Fastening: powder-actuated (DX) and gas-actuated tools", "Diamond systems: core drilling, wall/floor saws", "Measuring: rotating/line lasers, laser distance meters"],
    },

    # ============================= EARTHING (5) ==============================
    {
        "slug": "lightning-protection-systems",
        "wa_name": "Lightning Protection Systems",
        "category": "earthing", "image": "prod-lightning.jpg",
        "name": "Lightning Protection Systems",
        "detail": "Early streamer emission air terminals, lightning rods and kits",
        "brands": ["Furse"],
        "description": "Early streamer emission (ESE) air terminals, conventional lightning rods and complete protection kits designed to intercept and safely conduct lightning strikes to earth. Furse systems are engineered to BS EN 62305 for building and structure protection across the UAE.",
        "sizes": ["ESE air terminal: 25µs–60µs advance time, protection radius up to 107m", "Conventional rod: 1m–6m mast lengths", "Down conductor: copper tape or stranded conductor", "Standard: BS EN 62305"],
    },
    {
        "slug": "earthing-systems",
        "wa_name": "Earthing Systems",
        "category": "earthing", "image": "prod-earthing.jpg",
        "name": "Earthing Systems",
        "detail": "Earth rods, earth plates, chemical earth electrodes",
        "brands": ["Furse"],
        "description": "Earth rods, earth plates and chemical earth electrodes for achieving low-resistance earth connections in soil conditions ranging from standard to high-resistivity. Furse earthing components form the foundation of a building's lightning and electrical safety earthing network.",
        "sizes": ["Earth rods: 12.5mm–17.2mm dia., 1.2m–3m sections", "Earth plates: 600x600mm, 900x900mm copper/GI", "Chemical earth electrode: for high-resistivity soil", "Coupling: threaded, driving stud"],
    },
    {
        "slug": "furse-copper-tape",
        "wa_name": "Furse Copper Tape",
        "category": "earthing", "image": "prod-copper-tape.jpg",
        "name": "Furse Copper Tape",
        "detail": "25x3mm and 40x4mm bare copper tape for earthing",
        "brands": ["Furse"],
        "description": "Bare copper tape used as down-conductors and bonding conductors in lightning protection and earthing installations. Furse copper tape is UV-stable, corrosion-resistant and suited to both surface-fixed and buried applications.",
        "sizes": ["Size: 25x3mm, 25x4mm, 40x4mm", "Material: high-conductivity bare copper", "Coil length: 25m, 50m rolls", "Fixings: saddles, tape clips at 1m centres"],
    },
    {
        "slug": "furse-air-terminals",
        "wa_name": "Furse Air Terminals",
        "category": "earthing", "image": "prod-air-terminal.jpg",
        "name": "Furse Air Terminals",
        "detail": "Stainless steel air terminals, masts and mounting hardware",
        "brands": ["Furse"],
        "description": "Stainless steel air terminals, masts and mounting hardware forming the strike-interception point of a lightning protection system. Furse air terminals are corrosion-resistant for long-term rooftop exposure.",
        "sizes": ["Terminal length: 300mm–6,000mm masts", "Material: 316 stainless steel", "Mounting: base plate, wall bracket, guy-wire kit", "Diameter: 10mm–16mm rod"],
    },
    {
        "slug": "protection-accessories",
        "wa_name": "Protection Accessories",
        "category": "earthing", "image": "prod-prot-acc.jpg",
        "name": "Protection Accessories",
        "detail": "Test links, bonds, clamps, surge protection devices",
        "brands": ["Furse"],
        "description": "Test links, bonding clamps and surge protection devices (SPDs) that complete a compliant lightning and earthing installation, allowing periodic earth resistance testing and equipotential bonding. Furse SPDs also protect sensitive electrical and electronic equipment from transient overvoltage.",
        "sizes": ["Test links: bolted and bolted-disconnect types", "Bonding clamps: for tape, rod, rebar connections", "SPD: Type 1, Type 2, Type 3 per BS EN 61643", "Rated discharge current: up to 100kA (Type 1)"],
    },

    # ============================== SANITARY (6) =============================
    {
        "slug": "sanitary-fittings-ware",
        "wa_name": "Sanitary Fittings &amp; Ware",
        "category": "sanitary", "image": "prod-sanitary.jpg",
        "name": "Sanitary Fittings & Ware",
        "detail": "WC pans, cisterns, bidets, washbasins and pedestals",
        "brands": ["RAK Ceramics", "Pegler"],
        "description": "WC pans, cisterns, bidets, washbasins and pedestals for bathroom and washroom installations, from wall-hung and floor-mounted to close-coupled configurations. RAK Ceramics and Pegler ranges suit both residential villas and commercial/hospitality projects.",
        "sizes": ["WC: close-coupled, wall-hung, floor-mounted", "Cistern: dual-flush 3L/6L water-saving", "Basin: countertop, wall-hung, pedestal", "Colour: white, and designer finishes on select ranges"],
    },
    {
        "slug": "water-heaters",
        "wa_name": "Water Heaters",
        "category": "sanitary", "image": "prod-water-heater.jpg",
        "name": "Water Heaters",
        "detail": "Electric storage, instant, solar water heaters 10L to 100L",
        "brands": ["Ariston", "Everhot"],
        "description": "Electric storage, instant and solar water heaters ranging from compact 10-litre point-of-use units to 100-litre storage cylinders for whole-home hot water supply. Ariston and Everhot ranges include energy-efficient insulation and safety thermostats suited to UAE water conditions.",
        "sizes": ["Capacity: 10L, 15L, 30L, 50L, 80L, 100L", "Type: storage (electric), instant, solar-assisted", "Power: 1.5kW–3kW (electric storage)", "Pressure rating: up to 8 bar"],
    },
    {
        "slug": "sensor-taps",
        "wa_name": "Sensor Taps",
        "category": "sanitary", "image": "prod-sensor-tap.jpg",
        "name": "Sensor Taps",
        "detail": "Infra-red touchless basin, kitchen and urinal sensor taps",
        "brands": ["GROHE", "SANWA"],
        "description": "Infra-red touchless sensor taps for basins, kitchens and urinals, reducing water wastage and improving hygiene in commercial washrooms and healthcare facilities. GROHE and SANWA sensor taps are available in mains-powered and battery-operated versions.",
        "sizes": ["Power: battery (4xAA/6V) or mains-powered", "Sensor range: adjustable 5cm–15cm", "Finish: chrome, matt black", "Application: basin, kitchen, urinal flush"],
    },
    {
        "slug": "mixer-taps-shower-sets",
        "wa_name": "Mixer Taps &amp; Shower Sets",
        "category": "sanitary", "image": "prod-shower.jpg",
        "name": "Mixer Taps & Shower Sets",
        "detail": "Basin mixers, bath mixers, shower heads and thermostatic sets",
        "brands": ["GROHE", "Milano"],
        "description": "Basin mixers, bath mixers, and overhead/handheld shower sets including thermostatic mixing valves for consistent water temperature control. GROHE and Milano ranges span budget commercial specification through to premium designer bathroom fittings.",
        "sizes": ["Basin/bath mixer: single lever, deck or wall mounted", "Shower set: overhead 200mm–300mm, handheld options", "Thermostatic: anti-scald temperature limiter", "Finish: chrome, brushed nickel, matt black"],
    },
    {
        "slug": "ceramics-tiles",
        "wa_name": "Ceramics &amp; Tiles",
        "category": "sanitary", "image": "prod-tiles.jpg",
        "name": "Ceramics & Tiles",
        "detail": "Porcelain, ceramic floor and wall tiles in various sizes",
        "brands": ["RAK Ceramics"],
        "description": "Porcelain and ceramic floor and wall tiles in a wide range of sizes and finishes for residential and commercial flooring, walls and facades. RAK Ceramics tiles offer slip-resistant and polished finish options to suit different areas of a project.",
        "sizes": ["Size: 300x300mm, 300x600mm, 600x600mm, 600x1200mm", "Finish: matt, polished, textured/anti-slip", "Thickness: 8mm–10mm (wall/floor)", "Application: floor, wall, facade"],
    },
    {
        "slug": "valves-fittings",
        "wa_name": "Valves &amp; Fittings",
        "category": "sanitary", "image": "prod-valve.jpg",
        "name": "Valves & Fittings",
        "detail": "Ball valves, gate valves, check valves, copper pipe fittings",
        "brands": ["Pegler", "GROHE"],
        "description": "Ball valves, gate valves, check valves and copper pipe fittings for plumbing and water distribution isolation and control. Pegler and GROHE valves are specified for both domestic and commercial water systems requiring dependable shut-off.",
        "sizes": ["Valve size: 15mm–100mm (1/2\"–4\")", "Type: ball valve, gate valve, check/non-return valve", "Material: brass, bronze, DZR brass", "Pressure rating: PN16–PN25"],
    },

    # ================================ SAFETY (6) ==============================
    {
        "slug": "safety-shoes",
        "wa_name": "Safety Shoes",
        "category": "safety", "image": "prod-safety-shoes.jpg",
        "name": "Safety Shoes",
        "detail": "Steel toe cap safety shoes, EN20345 certified, various styles",
        "brands": ["Vaultex"],
        "description": "Steel toe cap safety shoes, EN20345 certified, in a range of styles from low-cut trainers to full ankle boots, protecting site workers from impact and compression hazards. Vaultex safety footwear includes anti-slip, oil-resistant soles suited to construction sites.",
        "sizes": ["EU size: 38–48", "Toe cap: steel or composite", "Sole: anti-slip, oil-resistant, anti-static", "Standard: EN20345 S1/S1P/S3"],
    },
    {
        "slug": "safety-harness",
        "wa_name": "Safety Harness",
        "category": "safety", "image": "prod-harness.jpg",
        "name": "Safety Harness",
        "detail": "Full body safety harness, lanyards and fall arrest systems",
        "brands": ["Vaultex"],
        "description": "Full body safety harnesses, lanyards and fall arrest systems for work-at-height applications on construction sites and maintenance work. Vaultex harnesses meet international fall-protection standards with adjustable straps for a secure fit.",
        "sizes": ["Attachment points: 1-point, 2-point, 5-point", "Lanyard: shock-absorbing, 1.5m–2m", "Standard: EN361 (harness), EN355 (lanyard)", "Adjustment: universal size, quick-adjust buckles"],
    },
    {
        "slug": "safety-helmets",
        "wa_name": "Safety Helmets",
        "category": "safety", "image": "prod-helmet.jpg",
        "name": "Safety Helmets",
        "detail": "HDPE and ABS safety helmets, EN397 certified, various colours",
        "brands": ["Vaultex", "TUF-FIX"],
        "description": "HDPE and ABS safety helmets, EN397 certified, in a range of colours for site role identification (worker, supervisor, visitor). Vaultex and TUF-FIX helmets include adjustable ratchet headbands and optional chin straps and accessory slots.",
        "sizes": ["Material: HDPE or ABS shell", "Colour: white, yellow, blue, red, orange", "Standard: EN397 / ANSI Z89.1", "Adjustment: ratchet headband, 6-point suspension"],
    },
    {
        "slug": "ear-plugs-protectors",
        "wa_name": "Ear Plugs &amp; Protectors",
        "category": "safety", "image": "prod-ear-plug.jpg",
        "name": "Ear Plugs & Protectors",
        "detail": "Disposable foam ear plugs and reusable ear defenders",
        "brands": ["Vaultex"],
        "description": "Disposable foam ear plugs and reusable ear defenders (earmuffs) for hearing protection in high-noise construction and industrial environments. Vaultex hearing protection products offer a range of noise reduction ratings (NRR) to suit different site exposure levels.",
        "sizes": ["Foam plugs: NRR 29dB–33dB, disposable/corded", "Earmuffs: NRR 24dB–30dB, over-ear/helmet-mount", "Pack: bulk box of 100–200 pairs (plugs)", "Colour: high-visibility orange/yellow"],
    },
    {
        "slug": "safety-gloves",
        "wa_name": "Safety Gloves",
        "category": "safety", "image": "prod-gloves.jpg",
        "name": "Safety Gloves",
        "detail": "Cut resistant, chemical resistant and general purpose gloves",
        "brands": ["Vaultex", "TUF-FIX"],
        "description": "Cut-resistant, chemical-resistant and general-purpose work gloves for handling materials, tools and chemicals safely on site. Vaultex and TUF-FIX ranges cover leather, nitrile-coated and cut-level 5 rated gloves for different task hazards.",
        "sizes": ["Size: S, M, L, XL, XXL", "Type: leather, nitrile-coated, cut-resistant (Level A-F)", "Cuff: knitted, gauntlet", "Standard: EN388 mechanical hazard rating"],
    },
    {
        "slug": "coveralls-hi-vis-vests",
        "wa_name": "Coveralls &amp; Hi-Vis Vests",
        "category": "safety", "image": "prod-hi-vis.jpg",
        "name": "Coveralls & Hi-Vis Vests",
        "detail": "Disposable and reusable coveralls, high visibility safety vests",
        "brands": ["Vaultex"],
        "description": "Disposable and reusable coveralls together with high-visibility safety vests for site PPE compliance and worker visibility around vehicles and machinery. Vaultex hi-vis products meet EN ISO 20471 visibility class requirements.",
        "sizes": ["Coverall size: S–3XL, disposable and reusable fabric", "Hi-vis class: Class 1, Class 2 (EN ISO 20471)", "Colour: orange, yellow with reflective tape", "Type: coverall, vest, jacket"],
    },

    # ================================= HVAC (6) ===============================
    {
        "slug": "copper-coils-tubes",
        "wa_name": "Copper Coils &amp; Tubes",
        "category": "hvac", "image": "prod-copper-coil.jpg",
        "name": "Copper Coils & Tubes",
        "detail": "ACR copper tubes and coils for refrigeration and air conditioning",
        "brands": ["Maksal", "Mueller"],
        "description": "ACR-grade copper tubes and coils for refrigeration and air conditioning pipework, cleaned, dehydrated and capped for direct system installation. Maksal and Mueller copper coils are supplied in soft-annealed coil form for easy on-site bending.",
        "sizes": ["Diameter: 1/4\"–1-3/8\" (6.35mm–34.9mm)", "Wall thickness: 0.71mm–1.24mm typical ACR gauge", "Coil length: 15m, 30m, 50m", "Standard: ASTM B280 (ACR grade)"],
    },
    {
        "slug": "pipe-insulation-aerofoam",
        "wa_name": "Pipe Insulation Aerofoam",
        "category": "hvac", "image": "prod-insulation.jpg",
        "name": "Pipe Insulation (Aerofoam)",
        "detail": "Elastomeric foam insulation tubes and sheets for AC pipes",
        "brands": ["Aerofoam", "GoFlex"],
        "description": "Elastomeric closed-cell foam insulation tubes and sheets for AC refrigerant and chilled water pipework, preventing condensation and heat gain. Aerofoam and GoFlex products carry class-O fire rating suited to UAE civil defence requirements.",
        "sizes": ["Tube diameter: 6mm–114mm bore", "Wall thickness: 9mm, 13mm, 19mm, 25mm", "Fire rating: Class O / Class 1", "Length: 2m tube lengths"],
    },
    {
        "slug": "sheet-insulation",
        "wa_name": "Sheet Insulation",
        "category": "hvac", "image": "prod-sheet-ins.jpg",
        "name": "Sheet Insulation",
        "detail": "Closed cell rubber insulation sheets for ductwork and tanks",
        "brands": ["Gulf-O-Flex"],
        "description": "Closed-cell rubber insulation sheets for ductwork, tanks and large flat/curved surfaces requiring thermal and condensation control. Gulf-O-Flex sheet insulation is self-adhesive backed for straightforward site application.",
        "sizes": ["Thickness: 6mm–50mm", "Sheet size: 1m x 8m rolls (typical)", "Backing: plain or self-adhesive", "Fire rating: Class O"],
    },
    {
        "slug": "refrigerant-gas",
        "wa_name": "Refrigerant Gas",
        "category": "hvac", "image": "prod-refrigerant.jpg",
        "name": "Refrigerant Gas",
        "detail": "R22, R32, R410A, R404A refrigerant gases in cylinders",
        "brands": ["Refron", "Mafron"],
        "description": "R22, R32, R410A and R404A refrigerant gases supplied in cylinders for charging and servicing air conditioning and refrigeration systems. Refron and Mafron gases are supplied in disposable and refillable cylinder options.",
        "sizes": ["Cylinder size: 800g, 2kg, 11.3kg, 13.6kg", "Refrigerant type: R22, R32, R410A, R404A", "Cylinder type: disposable, refillable", "Purity: AHRI-certified"],
    },
    {
        "slug": "hvac-controls",
        "wa_name": "HVAC Controls",
        "category": "hvac", "image": "prod-hvac-control.jpg",
        "name": "HVAC Controls",
        "detail": "Thermostats, pressure switches, expansion valves and controls",
        "brands": ["Honeywell", "Heidelberg"],
        "description": "Thermostats, pressure switches, expansion valves and control accessories for regulating and safeguarding air conditioning and refrigeration systems. Honeywell and Heidelberg controls range from simple room thermostats to programmable BMS-integrated devices.",
        "sizes": ["Thermostat: mechanical, digital, programmable/BMS", "Pressure switch: adjustable high/low cut-out", "Expansion valve: TXV/TEV, 1–15 ton capacity", "Voltage: 24V, 230V control circuits"],
    },
    {
        "slug": "hvac-accessories",
        "wa_name": "HVAC Accessories",
        "category": "hvac", "image": "prod-hvac-acc.jpg",
        "name": "HVAC Accessories",
        "detail": "Filter driers, sight glasses, service valves, flaring tools",
        "brands": ["Maksal", "Mueller"],
        "description": "Filter driers, sight glasses, service valves and flaring tools completing the accessory range for AC and refrigeration installation and servicing work. Maksal and Mueller accessories are stocked to support routine maintenance as well as new installations.",
        "sizes": ["Filter drier: 1/4\"–7/8\" line sizes", "Sight glass: with moisture indicator", "Service valve: ball type, 1/4\"–1-3/8\"", "Flaring tool: eccentric and standard flare kits"],
    },

    # ================================ LIGHTING (6) =============================
    {
        "slug": "track-lights",
        "wa_name": "Track Lights",
        "category": "lighting", "image": "prod-track-light.jpg",
        "name": "Track Lights",
        "detail": "Single phase and three phase LED track lights, 10W to 50W",
        "brands": ["Philips", "OSRAM"],
        "description": "Single-phase and three-phase LED track lighting systems for flexible, repositionable accent and display lighting in retail and commercial interiors. Philips and OSRAM track fittings range from 10W to 50W with a choice of beam angles.",
        "sizes": ["Wattage: 10W–50W", "Beam angle: 15°, 24°, 36°, 60°", "Track type: single-circuit, 3-circuit", "Colour temperature: 3000K, 4000K, 6500K"],
    },
    {
        "slug": "panel-lights",
        "wa_name": "Panel Lights",
        "category": "lighting", "image": "prod-panel-light.jpg",
        "name": "Panel Lights",
        "detail": "LED panel lights 600x600, 1200x600, back-lit and edge-lit",
        "brands": ["Philips", "LGL"],
        "description": "LED ceiling panel lights in 600x600mm and 1200x600mm formats, back-lit and edge-lit, for offices, retail and commercial ceiling grids. Philips and LGL panels offer flicker-free, glare-controlled illumination with long-life LED drivers.",
        "sizes": ["Size: 600x600mm, 1200x600mm, 300x1200mm", "Wattage: 18W–72W", "Colour temperature: 3000K, 4000K, 6500K", "Type: back-lit, edge-lit"],
    },
    {
        "slug": "down-lights",
        "wa_name": "Down Lights",
        "category": "lighting", "image": "prod-downlight.jpg",
        "name": "Down Lights",
        "detail": "Recessed LED downlights, dimmable, various colour temperatures",
        "brands": ["OSRAM", "Philips"],
        "description": "Recessed LED downlights, dimmable, in a range of colour temperatures for general and accent lighting in ceilings. OSRAM and Philips downlights offer trimless, fixed and adjustable/gimbal options for different ceiling design requirements.",
        "sizes": ["Cut-out size: 75mm–225mm", "Wattage: 5W–30W", "Colour temperature: 2700K–6500K", "Type: fixed, adjustable/gimbal, trimless"],
    },
    {
        "slug": "spot-lights",
        "wa_name": "Spot Lights",
        "category": "lighting", "image": "prod-spotlight.jpg",
        "name": "Spot Lights",
        "detail": "Surface mounted and recessed LED spotlights, adjustable",
        "brands": ["Frater", "Selex"],
        "description": "Surface-mounted and recessed LED spotlights with adjustable beam direction, used for accent and feature lighting in retail, hospitality and residential interiors. Frater and Selex spotlight ranges include track-compatible and standalone ceiling models.",
        "sizes": ["Wattage: 5W–20W", "Beam angle: 24°, 36°, 45°", "Mounting: surface, recessed, track-adaptor", "Colour temperature: 3000K, 4000K"],
    },
    {
        "slug": "led-strips-profiles",
        "wa_name": "LED Strips &amp; Profiles",
        "category": "lighting", "image": "prod-led-strip.jpg",
        "name": "LED Strips & Profiles",
        "detail": "IP20 and IP65 LED strip lights, aluminum profiles and diffusers",
        "brands": ["Philips", "LGL"],
        "description": "IP20 (indoor) and IP65 (wet-area) LED strip lights with matching aluminium profiles and diffusers for cove, under-cabinet and architectural linear lighting. Philips and LGL strips are available in single-colour, tunable-white and RGB variants.",
        "sizes": ["LED density: 60, 120, 240 LEDs/m", "Wattage: 4.8W/m–19.2W/m", "IP rating: IP20 (indoor), IP65 (wet area)", "Profile: surface, recessed, corner aluminium channel"],
    },
    {
        "slug": "linear-lights",
        "wa_name": "Linear Lights",
        "category": "lighting", "image": "prod-linear-light.jpg",
        "name": "Linear Lights",
        "detail": "Suspended and recessed LED linear luminaires for offices",
        "brands": ["OSRAM", "Selex"],
        "description": "Suspended and recessed LED linear luminaires providing uniform general illumination for offices, corridors and commercial spaces. OSRAM and Selex linear fittings are available in continuous-run and standalone lengths with high-efficiency optics.",
        "sizes": ["Length: 600mm, 1200mm, 1500mm, continuous run", "Wattage: 20W–60W", "Mounting: suspended, surface, recessed", "Colour temperature: 3000K, 4000K, 6500K"],
    },

    # ================================= PUMPS (6) ================================
    {
        "slug": "water-pumps-centrifugal",
        "wa_name": "Water Pumps Centrifugal",
        "category": "pumps", "image": "prod-centrifugal-pump.jpg",
        "name": "Water Pumps (Centrifugal)",
        "detail": "Single stage centrifugal pumps for domestic and commercial use",
        "brands": ["Grundfos", "ESPA"],
        "description": "Single-stage centrifugal water pumps for general domestic and commercial water transfer and circulation duties. Grundfos and ESPA pumps offer a range of flow/head performance curves to suit villa, building and irrigation applications.",
        "sizes": ["Flow rate: up to 300 LPM", "Head: up to 60m", "Power: 0.37kW–7.5kW (0.5HP–10HP)", "Connection: 1\"–3\" threaded/flanged"],
    },
    {
        "slug": "pressure-kit-pressure-sets",
        "wa_name": "Pressure Kit Pressure Sets",
        "category": "pumps", "image": "prod-pressure-pump.jpg",
        "name": "Pressure Kit / Pressure Sets",
        "detail": "Complete pressure booster sets with pressure tank and controls",
        "brands": ["ESPA", "Grundfos"],
        "description": "Complete pressure booster sets combining a pump, pressure tank and automatic pressure switch/controller, delivering consistent water pressure for domestic plumbing systems. ESPA and Grundfos pressure kits are pre-assembled for straightforward installation.",
        "sizes": ["Tank size: 24L–100L", "Pump power: 0.37kW–1.5kW", "Pressure setting: 1.5–4.0 bar adjustable", "Connection: 1\"–1.5\" inlet/outlet"],
    },
    {
        "slug": "transfer-pumps",
        "wa_name": "Transfer Pumps",
        "category": "pumps", "image": "prod-transfer-pump.jpg",
        "name": "Transfer Pumps",
        "detail": "Portable transfer pumps for water and non-corrosive liquids",
        "brands": ["Vespa", "ESPA"],
        "description": "Portable transfer pumps for moving water and non-corrosive liquids between tanks, tankers and containers on site. Vespa and ESPA transfer pumps are lightweight and suited to temporary dewatering and liquid-transfer tasks.",
        "sizes": ["Flow rate: up to 200 LPM", "Head: up to 40m", "Power: 0.37kW–2.2kW", "Connection: 1\"–2\" hose/threaded"],
    },
    {
        "slug": "booster-pumps",
        "wa_name": "Booster Pumps",
        "category": "pumps", "image": "prod-booster-pump.jpg",
        "name": "Booster Pumps",
        "detail": "In-line booster pumps for increasing water pressure",
        "brands": ["Grundfos", "ESPA"],
        "description": "In-line booster pumps for increasing water pressure at the point of use, commonly installed on shower, tap and irrigation feed lines with insufficient mains pressure. Grundfos and ESPA booster pumps include automatic flow-sensing on/off control.",
        "sizes": ["Flow rate: up to 60 LPM", "Pressure boost: up to 3 bar", "Power: 90W–370W", "Connection: 3/4\"–1\" threaded"],
    },
    {
        "slug": "control-panels-for-pumps",
        "wa_name": "Control Panels for Pumps",
        "category": "pumps", "image": "prod-pump-panel.jpg",
        "name": "Control Panels for Pumps",
        "detail": "Motor starter panels, VFD panels and pump control panels",
        "brands": ["Grundfos"],
        "description": "Motor starter panels and variable frequency drive (VFD) panels for controlling single and multi-pump sets, including duty/standby and duty/assist configurations. Grundfos pump control panels protect against dry-running, overload and phase failure.",
        "sizes": ["Motor rating: up to 30kW", "Starter type: DOL, star-delta, soft-start, VFD", "Configuration: single pump, duty/standby, multi-pump", "Protection: dry-run, overload, phase failure"],
    },
    {
        "slug": "submersible-pumps",
        "wa_name": "Submersible Pumps",
        "category": "pumps", "image": "prod-submersible.jpg",
        "name": "Submersible Pumps",
        "detail": "Borehole and drainage submersible pumps, various head ratings",
        "brands": ["Grundfos", "ESPA"],
        "description": "Borehole and drainage submersible pumps for groundwater extraction and dewatering applications, with various head ratings to suit borehole depth and duty requirements. Grundfos and ESPA submersibles feature corrosion-resistant stainless steel construction.",
        "sizes": ["Flow rate: up to 500 LPM", "Head: up to 150m (borehole), up to 20m (drainage)", "Power: 0.37kW–15kW", "Material: stainless steel housing and impellers"],
    },

    # ================================ HARDWARE (15) =============================
    {
        "slug": "steel-nails",
        "wa_name": "Steel Nails",
        "category": "hardware", "image": "prod-nails.jpg",
        "name": "Steel Nails",
        "detail": "Common wire nails, masonry nails, roofing nails in all sizes",
        "brands": ["General"],
        "description": "Common wire nails, masonry nails and roofing nails in a full range of sizes for general construction, carpentry and fixing applications. Supplied loose or boxed in bulk quantities for site use.",
        "sizes": ["Length: 25mm–150mm", "Type: common wire, masonry (hardened), roofing (umbrella head)", "Finish: bright steel, galvanized", "Pack: bulk box, 1kg/5kg/25kg"],
    },
    {
        "slug": "screws",
        "wa_name": "Screws",
        "category": "hardware", "image": "prod-screws.jpg",
        "name": "Screws",
        "detail": "Wood screws, self-tapping, drywall, machine screws",
        "brands": ["General"],
        "description": "Wood screws, self-tapping screws, drywall screws and machine screws covering general fixing needs across timber, metal and plasterboard. Supplied in a range of head types and drive systems for different fastening applications.",
        "sizes": ["Length: 12mm–150mm", "Type: wood, self-tapping, drywall, machine", "Drive: Phillips, Pozidriv, Torx, slotted", "Finish: zinc plated, black phosphate, stainless"],
    },
    {
        "slug": "nuts-bolts",
        "wa_name": "Nuts &amp; Bolts",
        "category": "hardware", "image": "prod-nuts-bolts.jpg",
        "name": "Nuts & Bolts",
        "detail": "Hex bolts, carriage bolts, stainless and galvanized nuts and bolts",
        "brands": ["General"],
        "description": "Full range of hex bolts, carriage bolts, and matching nuts in mild steel (zinc/galvanized finish) and stainless steel (A2/A4 grade) for structural, fabrication and general construction fastening. Supplied loose or boxed in bulk quantities for site and workshop use.",
        "sizes": ["Diameter: M6, M8, M10, M12, M16, M20, M24", "Length: 20mm – 300mm", "Finish: zinc plated, hot-dip galvanized, stainless steel A2/A4", "Grade: 4.6, 8.8, 10.9"],
    },
    {
        "slug": "anchor-bolts",
        "wa_name": "Anchor Bolts",
        "category": "hardware", "image": "prod-anchor-bolt.jpg",
        "name": "Anchor Bolts",
        "detail": "Chemical anchors, expansion anchors, sleeve anchors",
        "brands": ["General"],
        "description": "Chemical anchors, mechanical expansion anchors and sleeve anchors for fixing into concrete and masonry substrates, used for structural fixings, machinery mounting and safety-critical installations. Rated load capacities available on request for engineered applications.",
        "sizes": ["Diameter: M6–M24", "Type: mechanical expansion, chemical injection, sleeve anchor", "Length: 50mm–300mm", "Substrate: concrete, solid/hollow masonry"],
    },
    {
        "slug": "wire-rope-clips-d-shackles",
        "wa_name": "Wire Rope Clips &amp; D-Shackles",
        "category": "hardware", "image": "prod-wire-rope.jpg",
        "name": "Wire Rope Clips & D-Shackles",
        "detail": "Galvanized wire rope clips, bow shackles and D-shackles",
        "brands": ["General"],
        "description": "Galvanized wire rope clips (bulldog grips), bow shackles and D-shackles for rigging, lifting and general wire rope termination work. Suited to construction lifting, signage and general securing applications.",
        "sizes": ["Wire rope diameter: 3mm–32mm (clips)", "Shackle WLL: 0.5T–20T", "Material: galvanized steel, drop-forged shackles", "Type: bow shackle, D-shackle, wire rope clip"],
    },
    {
        "slug": "ladders",
        "wa_name": "Ladders",
        "category": "hardware", "image": "prod-ladder.jpg",
        "name": "Ladders",
        "detail": "Aluminium step ladders, extension ladders and platform steps",
        "brands": ["General"],
        "description": "Aluminium step ladders, extension ladders and platform steps for site and maintenance access work. Lightweight, corrosion-resistant construction with non-slip feet and locking mechanisms for safe use.",
        "sizes": ["Step ladder: 2–12 steps", "Extension ladder: 2-section, 3-section, up to 8m extended", "Platform steps: 2–6 steps with top platform", "Material: aluminium, load rating up to 150kg"],
    },
    {
        "slug": "wheelbarrow-platform-trolley",
        "wa_name": "Wheelbarrow &amp; Platform Trolley",
        "category": "hardware", "image": "prod-wheelbarrow.jpg",
        "name": "Wheelbarrow & Platform Trolley",
        "detail": "Heavy duty construction wheelbarrows and flat platform trolleys",
        "brands": ["General"],
        "description": "Heavy-duty construction wheelbarrows and flat platform trolleys for moving materials, debris and equipment around site. Puncture-resistant or pneumatic tyre options for rough site terrain.",
        "sizes": ["Wheelbarrow capacity: 65L–100L", "Trolley load capacity: 150kg–300kg", "Wheel type: pneumatic, puncture-proof", "Frame: galvanized/powder-coated steel"],
    },
    {
        "slug": "ms-tube-steel-sections",
        "wa_name": "MS Tube &amp; Steel Sections",
        "category": "hardware", "image": "prod-steel-tube.jpg",
        "name": "MS Tube & Steel Sections",
        "detail": "Mild steel hollow sections, RHS, SHS for fabrication",
        "brands": ["General"],
        "description": "Mild steel hollow sections — RHS (rectangular) and SHS (square) — plus round tube for structural fabrication, railings, frames and general steelwork. Supplied in standard mill lengths for cutting to project requirements.",
        "sizes": ["RHS/SHS: 20x20mm–150x100mm", "Round tube: 15mm–100mm diameter", "Wall thickness: 1.5mm–5mm", "Length: 6m standard mill length"],
    },
    {
        "slug": "polythene-sheets-tarpauline",
        "wa_name": "Polythene Sheets &amp; Tarpauline",
        "category": "hardware", "image": "prod-tarpaulin.jpg",
        "name": "Polythene Sheets & Tarpauline",
        "detail": "DPM polythene, builder's film, heavy duty tarpaulins",
        "brands": ["General"],
        "description": "Damp-proof membrane (DPM) polythene, builder's film and heavy-duty tarpaulins for weather protection, curing, and covering materials and works on site. UV-stabilised heavy-duty tarpaulin options withstand extended outdoor exposure.",
        "sizes": ["DPM thickness: 250 micron, 500 micron, 1000 micron", "Tarpaulin size: 3x4m–12x18m", "Roll width: 2m–8m (polythene sheet)", "Colour: clear, black, blue (tarpaulin)"],
    },
    {
        "slug": "thermocol-sheets",
        "wa_name": "Thermocol Sheets",
        "category": "hardware", "image": "prod-thermocol.jpg",
        "name": "Thermocol Sheets",
        "detail": "EPS expanded polystyrene boards for insulation and packaging",
        "brands": ["General"],
        "description": "EPS (expanded polystyrene) foam boards for thermal insulation, void-filling and protective packaging applications in construction. Lightweight, easy to cut and shape on site.",
        "sizes": ["Thickness: 25mm–100mm", "Sheet size: 1200x600mm, 2400x1200mm", "Density: 12kg/m³–24kg/m³", "Application: roof/wall insulation, packaging void-fill"],
    },
    {
        "slug": "masking-tape",
        "wa_name": "Masking Tape",
        "category": "hardware", "image": "prod-masking-tape.jpg",
        "name": "Masking Tape",
        "detail": "General purpose and high temperature masking tape rolls",
        "brands": ["General"],
        "description": "General-purpose and high-temperature masking tape rolls for paint line masking, surface protection and temporary bundling on site. High-temperature grades suit powder-coating and spray-painting applications.",
        "sizes": ["Width: 12mm, 24mm, 36mm, 48mm, 72mm", "Length: 40m, 50m rolls", "Temperature grade: standard, high-temp (up to 120°C)", "Adhesion: crepe paper, easy clean-release"],
    },
    {
        "slug": "duct-tape",
        "wa_name": "Duct Tape",
        "category": "hardware", "image": "prod-duct-tape.jpg",
        "name": "Duct Tape",
        "detail": "Heavy duty cloth duct tape, aluminium foil tape",
        "brands": ["General"],
        "description": "Heavy-duty cloth duct tape and aluminium foil tape for sealing, bundling, and repair work across construction and HVAC ductwork applications. High tack adhesive holds securely to a wide range of surfaces.",
        "sizes": ["Width: 48mm, 72mm, 96mm", "Length: 25m, 50m rolls", "Type: cloth duct tape, aluminium foil tape", "Colour: silver, black, other on request"],
    },
    {
        "slug": "insulation-tape",
        "wa_name": "Insulation Tape",
        "category": "hardware", "image": "prod-ins-tape.jpg",
        "name": "Insulation Tape",
        "detail": "PVC electrical insulation tape in various colours",
        "brands": ["General"],
        "description": "PVC electrical insulation tape in a full range of colours for wire identification and insulating electrical joints and terminations. Flame-retardant PVC construction suited to general electrical installation work.",
        "sizes": ["Width: 18mm, 19mm", "Length: 10m, 20m rolls", "Colour: red, yellow, blue, black, green/yellow, white", "Rating: flame-retardant PVC, up to 600V"],
    },
    {
        "slug": "spanners-hand-tools",
        "wa_name": "Spanners &amp; Hand Tools",
        "category": "hardware", "image": "prod-spanner.jpg",
        "name": "Spanners & Hand Tools",
        "detail": "Open end, ring, combination spanners; pipe wrenches",
        "brands": ["Stanley"],
        "description": "Open-end, ring and combination spanners along with pipe wrenches for general mechanical and plumbing fastening work. Stanley-supplied sets cover metric and imperial sizing for site and workshop toolkits.",
        "sizes": ["Spanner size: 6mm–32mm / 1/4\"–1-1/4\"", "Type: open-end, ring, combination", "Pipe wrench: 8\"–24\" length", "Material: chrome vanadium steel"],
    },
    {
        "slug": "spirit-level-manhole-cover",
        "wa_name": "Spirit Level &amp; Manhole Cover",
        "category": "hardware", "image": "prod-spirit-level.jpg",
        "name": "Spirit Level & Manhole Cover",
        "detail": "Professional spirit levels; cast iron and polymer manhole covers",
        "brands": ["General"],
        "description": "Professional spirit levels for accurate levelling and alignment work, alongside cast iron and polymer manhole covers for drainage and utility access points. A practical pairing of site measurement and civil works materials.",
        "sizes": ["Spirit level length: 300mm–2400mm", "Manhole cover load class: B125, D400 (cast iron)", "Manhole cover size: 450mm–600mm clear opening", "Material: aluminium level body; cast iron/polymer cover"],
    },
]
